name: Deploy Cosmos DB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Cosmos DB
        run: |
          az deployment group create \
            --resource-group <resource-group-name> \
            --template-file <path-to-bicep-template> \
            --parameters <path-to-parameters-file>