name: Deploy API to APIM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy API to APIM
        uses: azure/api-management-update@v0
        with:
          apim-service-name: <APIM_SERVICE_NAME>
          resource-group: <RESOURCE_GROUP_NAME>
          api-id: <API_ID>
          api-revision: <API_REVISION>
          openapi-spec: <PATH_TO_OPENAPI_SPEC>